apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: gitlab-managed-apps
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: auth-dev-api
  namespace: gitlab-managed-apps
spec:
  selector:
    app: auth-dev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
