apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: gitlab-managed-apps
  labels:
    app: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: clyde.local:5005/taliesin/micro-auth/master:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MICRO_ENVIRONMENT
              value: "production"
            - name: DB_HOST
              value: "10.133.33.51"
            - name: DB_PORT
              value: "3306"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-db-secrets
                  key: password
            - name: HMAC_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-hmac-secrets
                  key: secret
          resources:
            requests:
              cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-dev
  namespace: gitlab-managed-apps
  labels:
    app: auth-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: auth-dev
    spec:
      containers:
        - name: auth-dev
          image: clyde.local:5005/taliesin/micro-auth/master:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MICRO_ENVIRONMENT
              value: "dev"
            - name: DB_HOST
              value: "10.133.33.51"
            - name: DB_PORT
              value: "3306"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-db-secrets
                  key: password
            - name: HMAC_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-hmac-secrets
                  key: secret
          resources:
            requests:
              cpu: "75m"
