apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: gitlab-managed-apps
  labels:
    app: auth
spec:
  selector:
    app: auth
  ports:
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api-dev
  namespace: gitlab-managed-apps
  labels:
    app: auth-dev
spec:
  selector:
    app: auth-dev
  ports:
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080
